Linux, Macのビルドを直す
VOICEVOX/open_jtalk pull request #5
Opened 2022-04-29 22:38 UTC by Yosshi999

#4 でlinuxとmacのビルドが通らなくなっていた（参照：https://github.com/VOICEVOX/voicevox_core/pull/119）

ソースを直すとともに、CIを動作させ再発防止する

2022-04-29 22:49 UTC, Yosshi999 commented
メモ

https://www.jpcert.or.jp/sc-rules/c-dcl09-c.html

> 注：EINVAL と EIO は C 標準では定義されていないが、大概の処理系では利用可能であり、POSIX には定義されている。

2022-04-29 23:04 UTC, Yosshi999 commented
errnoの使用を取り消した。代わりにenumを定義した

2022-05-02 08:21 UTC, y-chan approved these changes
LGTMですー！
コード自体は問題ないですが、ちょっと書式というか、変わってた部分があったので、suggestしておきました。

2022-05-02 08:21 UTC, y-chan commented on .github/workflows/ccpp.yaml
> +    branches: [ '1.10', '1.11']
```suggestion
    branches: [ '1.10', '1.11' ]
```

細かいですが、スペースが消えてしまっていて、ちょっと他と書式が変っちゃってるので念のためコメントしておきます

2022-05-02 08:27 UTC, y-chan commented on .github/workflows/ccpp.yaml
> +    branches: [ '1.10', '1.11']
あ、これはupstream側のコード変更なんですね、こちらで不用意に触らない方がいいと思ったので、このsuggestionは取り下げます

2022-05-02 12:25 UTC, PickledChair requested changes
おそらく全体的には大丈夫だと思いました！

一部 typo を発見したので修正よろしくお願いします……！

2022-05-02 12:25 UTC, PickledChair commented on src/text2mecab/text2mecab.c
> +      return TEXT2MEACB_RESULT_INVALID_ARGUMENT;
typo を見つけました
```suggestion
      return TEXT2MECAB_RESULT_INVALID_ARGUMENT;
```

2022-05-02 12:25 UTC, PickledChair commented on src/text2mecab/text2mecab.h
> +    TEXT2MEACB_RESULT_INVALID_ARGUMENT = 1,
typo を見つけました
```suggestion
    TEXT2MECAB_RESULT_INVALID_ARGUMENT = 1,
```

2022-05-02 12:44 UTC, Yosshi999 commented on src/text2mecab/text2mecab.h
> +    TEXT2MEACB_RESULT_INVALID_ARGUMENT = 1,
ありがとうございます！修正しました

2022-05-02 12:47 UTC, PickledChair approved these changes
LGTM！

2022-05-02 13:22 UTC, merged