Add: Mecab_load_with_userdicを追加
VOICEVOX/open_jtalk pull request #9
Opened 2023-07-09 02:52 UTC by sevenc-nanashi

## 内容

Mecab_load_with_userdicを追加します。

## 関連 Issue

- ref: voicevox/voicevox_core#265

## スクリーンショット・動画など

（なし）

## その他

（なし）

2023-07-09 09:19 UTC, Hiroshiba commented
@sevenc-nanashi PRありです！！

もし知ってたらお聞きしたいのですが、この関数がなくてもpyopenjtalkの方はuserdicを読み込めてたのはなぜなんでしょう･･･？
（同じ方法を使えばこの関数がなくてもuserdicが読み込めるのかなと思った次第です。）

2023-07-09 09:21 UTC, sevenc-nanashi commented
https://github.com/VOICEVOX/pyopenjtalk/blob/827a3fc5c7dda7bbe832c0c69da98e39cc8cb2c3/pyopenjtalk/openjtalk.pyx#L28-L55

ユーザー辞書指定がなければMecab_load、指定されていたらMecab_load_with_userdic（のようなもの）をCPythonで実装、のようになっています。

2023-07-09 20:30 UTC, Hiroshiba requested changes
エラーメッセージを書くところ以外はlgtmです！！

2023-07-09 20:30 UTC, Hiroshiba commented on src/mecab/src/mecab.cpp
> +
エラーメッセージをどう的に定義するのではなく、エラーメッセージを表示する関数を作っておくのはどうでしょう。
free忘れのメモリリークも防止できたり、64文字プラスする部分もなくなって簡潔になるはず。

こんな感じ･･･？

```c
void print_error(const char *dicdir, const char *userdic) {
    if (userdic == NULL) {
        fprintf(stderr, "ERROR: Mecab_load() in mecab.cpp: Cannot open %s.\n", dicdir);
    } else {
        fprintf(stderr, "ERROR: Mecab_load() in mecab.cpp: Cannot open %s or %s.\n", dicdir, userdic);
    }
}
```

（cppだから関数内関数がありそうですが）

参考：[ChatGPT君](https://chat.openai.com/share/6d0555da-8f83-43d9-b067-7c23acbcc4ea)

2023-07-09 20:30 UTC, Hiroshiba commented on src/mecab/src/mecab.cpp
> +    } else {
```suggestion
   } else {
```

2023-07-09 20:30 UTC, Hiroshiba commented on src/mecab/src/mecab.cpp
> +    return Mecab_load_with_userdic(m, dicdir, NULL);
```suggestion
   return Mecab_load_with_userdic(m, dicdir, NULL);
```

2023-07-09 20:31 UTC, Hiroshiba commented
あ、pyopenjtalk側もこれ使うようにするのが良いかもですかね。
マージ後にisuse立てときますか！（忘れそう）

2023-07-09 20:58 UTC, sevenc-nanashi commented
レビューを反映しました。

> あ、pyopenjtalk側もこれ使うようにするのが良いかもですかね。

確かに。良さそう。

2023-07-10 00:42 UTC, Hiroshiba approved these changes
LGTM！！！

辞書に詳しい @takana-v さんももしよかったらちょっと眺めていただけると心強いです･･･！！

@y-chan VOICEVOXのopenjtalkに珍しく機能追加が入るので共有です 🙏

2023-07-10 10:18 UTC, takana-v approved these changes
（C++に詳しくないのでちょっと自信無いですが）LGTM！

2023-07-10 11:10 UTC, sevenc-nanashi commented
Approve集まったのでマージします。

2023-07-10 11:10 UTC, merged

2023-07-11 00:02 UTC, qryxip commented on src/mecab/src/mecab.cpp
> +void Mecab_print_load_error(const char *dicdir, const char *userdic) {
今言うのは微妙ですが、ここは`static void`にして`Mecab_`というprefixを外した方がよかった気がします。

2023-07-11 03:17 UTC, Hiroshiba commented on src/mecab/src/mecab.cpp
> +void Mecab_print_load_error(const char *dicdir, const char *userdic) {
たしかに。private関数だから`Mecab_`いらなかった。